### PR TITLE
SDK package size cleanup

### PR DESCRIPTION
**Pull request by j-berman**
- Removed corejs3 polyfill to allow developers to use their own polyfills/not pollute globals (more on this [here](https://babeljs.io/docs/en/babel-plugin-transform-runtime#why)).
- Replaced axios with XMLHtthRequest.

Thanks to @rhucle for the suggestions in #133

### CODE REVIEW

**Comment by adaddeo** [comment]
Good points. Nixing Axios is good and polyfill dependencies shouldn't be shipped in the cjs build but I think it should still be shipped in the umd build that is for directly including via a script tag since the user is expecting it to work and no further bundling is happening where core-js polyfill and runtime can be included. Move the config change from the `webpack.common.js` to `webpack.cjs.js`.

**Comment by clintonbloodworth** [comment]
I don't know if there's reason to think of the UMD build any differently than the module one. Just because the user wishes to consume the client library using a script tag instead of a bundler doesn't mean she's signing up for a giant bundle that runs in almost every browser environment. 

And just as easily as she included a script tag for UserBase client, she can include one linking to `core-js` on a CDN. There's nothing about UMD that implies it's comprehensive with respect to browser support.

Anyway, my two cents. ¯\_(ツ)_/¯

**Comment by adaddeo** [comment]
Completely valid two cents.

The reason, and to your point a completely arbitrary one that isn't in anyway implied by UMD, would be to provide a very simple option that "just worked" (w/o the need to rely on a separate CDN and w/o the need to include a much larger set of polyfills than strictly needed) alongside the CJS and ESM distributions that allow for more sophisticated setups.

**Comment by j-berman** [comment]
Both good points. As discussed, going to move forward with a single compatibility list for all builds (UMD, CJS, and ESM). UMD will therefore also exclude core-js. Will also include clear documentation as to which browsers are supported + explicit details on which polyfills could be used to support a larger set of browsers.

**Pull request merged**
